CREATE IF NOT EXISTS TABLE USER_TBL (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    IS_DRIVER BIT(1) NOT NULL DEFAULT 0,
    IS_ADMIN BIT(1) NOT NULL DEFAULT 0,
    GRADE CHAR(2) CHECK(GRADE IN ('F','SM','J','SN','G')),
    LIVE_ON_CAMPUS BIT(1)
);

